# Generated by Django 4.1.5 on 2023-03-06 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('rank', models.CharField(max_length=512)),
                ('employee_number', models.IntegerField()),
                ('major', models.CharField(max_length=512)),
                ('certificate', models.CharField(max_length=512)),
                ('graduted_from', models.CharField(max_length=512)),
                ('job_title', models.CharField(max_length=512)),
                ('work_place', models.CharField(max_length=512)),
                ('writen_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
