# Generated by Django 4.1.5 on 2023-03-06 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('course_number', models.CharField(max_length=512)),
                ('course_provider', models.CharField(max_length=512)),
                ('course_provider_country', models.CharField(max_length=512)),
                ('where_course_has_been_provide', models.CharField(max_length=512)),
                ('degree_percent', models.FloatField()),
                ('rating_word', models.CharField(max_length=512)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('assigend_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('writen_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
