# Generated by Django 4.1.7 on 2023-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number_of_courses_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_mandate_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
