# Generated by Django 4.1.7 on 2023-03-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_number_of_courses_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number_of_courses_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number_of_mandate_days',
            field=models.IntegerField(default=0),
        ),
    ]
