# Generated by Django 4.1.5 on 2023-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_hijridate_course_endhijridate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='endhijridate',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='starthijridate',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
