# Generated by Django 4.1.7 on 2023-04-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mandate_endhijridate_mandate_starthijridate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.FileField(default='notexist', upload_to='pdfs/'),
        ),
    ]
