# Generated by Django 4.1.7 on 2023-04-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
    ]
