# Generated by Django 4.1.7 on 2023-04-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_course_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_upload',
            field=models.FileField(default='notexist', upload_to='pdfs/'),
        ),
    ]
