# Generated by Django 4.1.7 on 2023-04-10 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_certificate_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_upload',
        ),
    ]
