# Generated by Django 4.1.5 on 2023-04-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_course_course_certficate_upload_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
