# Generated by Django 4.1.5 on 2023-04-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=512)),
                ('activity_st_date', models.DateField()),
                ('activity_end_date', models.DateField()),
                ('full_start_hijri_date', models.CharField(max_length=512)),
                ('full_end_hijri_date', models.CharField(max_length=512)),
                ('employee_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('writen_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
