# Generated by Django 4.1.5 on 2023-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_hijri_day',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_hijri_month',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_hijri_year',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_hijri_day',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_hijri_month',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_hijri_year',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_hijri_day',
            field=models.CharField(default=11, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_hijri_month',
            field=models.CharField(default=11, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_hijri_year',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_hijri_day',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_hijri_month',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_hijri_year',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='end_hijri_day',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='end_hijri_month',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='end_hijri_year',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='start_hijri_day',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='start_hijri_month',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='start_hijri_year',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
