# Generated by Django 4.1.5 on 2023-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_activity_activity_in_out_activity_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_tack_action',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_in_out',
            field=models.CharField(choices=[('inside', 'inside'), ('outside', 'outside')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=10),
        ),
    ]
