# Generated by Django 4.1.5 on 2023-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_certficate_upload',
            field=models.ImageField(default='Certificat not avilibale', null=True, upload_to='static/pdfs/'),
        ),
    ]
