# Generated by Django 4.1.5 on 2023-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_employee_rank_employee_mulirty_classfication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='non_mulirty_classfication',
            field=models.CharField(choices=[('العاشرة', 'العاشره  '), ('الحادية عشر', ' الحادية عشر'), ('الثانية عشر', ' الثانية عشر'), (' الثالثة عشر', ' الثالثة عشر')], max_length=512, null=True),
        ),
    ]
