# Generated by Django 4.1.5 on 2023-09-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_employee_non_mulirty_classfication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mulirty_classfication',
            field=models.CharField(blank=True, choices=[('الرتبة العسكرية الاولى', 'الرتبة العسكرية الاولى'), ('الرتبة العسكرية الثانية', 'الرتبة العسكرية الثانية'), ('الرتبة العسكرية الثالثة', 'الرتبة العسكرية الثالثة'), ('الرتبة العسكرية الرابعة', 'الرتبة العسكرية الرابعة')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='non_mulirty_classfication',
            field=models.CharField(blank=True, choices=[('العاشرة', 'العاشره  '), ('الحادية عشر', ' الحادية عشر'), ('الثانية عشر', ' الثانية عشر'), (' الثالثة عشر', ' الثالثة عشر')], max_length=512, null=True),
        ),
    ]
