# Generated by Django 4.1.5 on 2023-09-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_employee_mulirty_classfication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='non_mulirty_classfication',
            field=models.CharField(blank=True, choices=[('الخامسة', 'الخامسة'), ('السادسة', 'السادسة'), ('السابعة', 'السابعة'), ('الثامنة', 'الثامنة'), ('التاسعة', 'التاسعة'), ('العاشرة', 'العاشرة'), ('الحادية عشر', ' الحادية عشر'), ('الثانية عشر', ' الثانية عشر'), ('الرابعة عشر', ' الثالثة عشر')], max_length=512, null=True),
        ),
    ]
